# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 09:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notif',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 1, 28, 14, 42, 53, 193314)),
        ),
    ]
