# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 09:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0002_auto_20180128_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='audio1',
            field=models.FileField(default='audios1/default.mp3', upload_to='audios1'),
        ),
        migrations.AlterField(
            model_name='notif',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 1, 28, 14, 50, 43, 615989)),
        ),
    ]
