# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0005_auto_20180308_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='total_level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totallevel', models.IntegerField(default=4)),
            ],
        ),
    ]
