# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0006_total_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='max_level',
            new_name='current_level',
        ),
    ]
